### ISSUE TITLE
希望在3.15版本中  增加 dialog 占屏幕比例 API入口  尤其是自定义dialog布局

### ISSUE THREAD

**Issue by yinking1203** [kongzue/DialogV3#76]
由于 商城类 应用  各种dialog  层出不穷   UI也会着重在这方面   期待大佬  早点开放

**Comment by kongzue** [comment]
目前有CustomDialog可以完全客制化Dialog，不清楚您需要哪种样式的对话框

**Comment by yinking1203** [comment]
&nbsp;&nbsp;





------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"notifications"<notifications@github.com&gt;;
发送时间:&nbsp;2019年10月31日(星期四) 下午5:10
收件人:&nbsp;"kongzue/DialogV3"<DialogV3@noreply.github.com&gt;;
抄送:&nbsp;"尹江峰"<526241452@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [kongzue/DialogV3] 希望在3.15版本中  增加 dialog 占屏幕比例 API入口  尤其是自定义dialog布局 (#76)




目前有CustomDialog可以完全客制化Dialog，不清楚您需要哪种样式的对话框

**Comment by yinking1203** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"notifications"<notifications@github.com&gt;;
发送时间:&nbsp;2019年10月31日(星期四) 下午5:14
收件人:&nbsp;"kongzue/DialogV3"<DialogV3@noreply.github.com&gt;;
抄送:&nbsp;"尹江峰"<526241452@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [kongzue/DialogV3] 希望在3.15版本中  增加 dialog 占屏幕比例 API入口  尤其是自定义dialog布局 (#76)




......？

**Comment by kongzue** [comment]
未收到您任何回复信息

**Comment by yinking1203** [comment]
额... &nbsp;难道是我没找到 设置dialog 高度 &nbsp;占屏幕多少的 &nbsp;方法吗?&nbsp;
&nbsp;比如 &nbsp;dialog &nbsp;高度 是屏幕的一半 &nbsp; 这些方法 就是问您一下 &nbsp;是不是没开发呢...


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"notifications"<notifications@github.com&gt;;
发送时间:&nbsp;2019年10月31日(星期四) 下午5:23
收件人:&nbsp;"kongzue/DialogV3"<DialogV3@noreply.github.com&gt;;
抄送:&nbsp;"尹江峰"<526241452@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [kongzue/DialogV3] 希望在3.15版本中  增加 dialog 占屏幕比例 API入口  尤其是自定义dialog布局 (#76)




未收到您任何回复信息

**Comment by kongzue** [comment]
CustomDialog可以设置从屏幕底端显示：
CustomDialog.setAlign(CustomDialog.ALIGN.BOTTOM)        //从屏幕底端出现
然后您可以只做一个一半屏幕高度的布局即可

**Comment by yinking1203** [comment]
&nbsp;麻烦您了 &nbsp; 嗯 &nbsp;setAlign 这个我知道 &nbsp;只是 写死高度 或者 依靠 margin &nbsp;来控制高度 &nbsp;会不会不太友好 适配的话 估计也会有问题
&nbsp;


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"notifications"<notifications@github.com&gt;;
发送时间:&nbsp;2019年10月31日(星期四) 下午5:32
收件人:&nbsp;"kongzue/DialogV3"<DialogV3@noreply.github.com&gt;;
抄送:&nbsp;"尹江峰"<526241452@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [kongzue/DialogV3] 希望在3.15版本中  增加 dialog 占屏幕比例 API入口  尤其是自定义dialog布局 (#76)




CustomDialog可以设置从屏幕底端显示：
 CustomDialog.setAlign(CustomDialog.ALIGN.BOTTOM)        //从屏幕底端出现
 然后您可以只做一个一半屏幕高度的布局即可

**Comment by kongzue** [comment]
您可以对您的view的layoutParameter设置屏幕高度除以2来实现，因这不属于DialogV3普遍需求功能所以我无法给您单独添加此功能，还请您理解

________________________________
发件人: yinking1203 <notifications@github.com>
发送时间: Thursday, October 31, 2019 5:41:31 PM
收件人: kongzue/DialogV3 <DialogV3@noreply.github.com>
抄送: Kongzue <myzcxhh@live.cn>; Comment <comment@noreply.github.com>
主题: Re: [kongzue/DialogV3] 希望在3.15版本中 增加 dialog 占屏幕比例 API入口 尤其是自定义dialog布局 (#76)

&nbsp;麻烦您了 &nbsp; 嗯 &nbsp;setAlign 这个我知道 &nbsp;只是 写死高度 或者 依靠 margin &nbsp;来控制高度 &nbsp;会不会不太友好 适配的话 估计也会有问题
&nbsp;


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"notifications"<notifications@github.com&gt;;
发送时间:&nbsp;2019年10月31日(星期四) 下午5:32
收件人:&nbsp;"kongzue/DialogV3"<DialogV3@noreply.github.com&gt;;
抄送:&nbsp;"尹江峰"<526241452@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [kongzue/DialogV3] 希望在3.15版本中 增加 dialog 占屏幕比例 API入口 尤其是自定义dialog布局 (#76)




CustomDialog可以设置从屏幕底端显示：
CustomDialog.setAlign(CustomDialog.ALIGN.BOTTOM) //从屏幕底端出现
然后您可以只做一个一半屏幕高度的布局即可

―
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.

―

**Comment by yinking1203** [comment]
&nbsp;好的 &nbsp;百忙之中 &nbsp;麻烦您了 &nbsp;


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"notifications"<notifications@github.com&gt;;
发送时间:&nbsp;2019年10月31日(星期四) 下午5:43
收件人:&nbsp;"kongzue/DialogV3"<DialogV3@noreply.github.com&gt;;
抄送:&nbsp;"尹江峰"<526241452@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [kongzue/DialogV3] 希望在3.15版本中  增加 dialog 占屏幕比例 API入口  尤其是自定义dialog布局 (#76)



您可以对您的view的layoutParameter设置屏幕高度除以2来实现，因这不属于DialogV3普遍需求功能所以我无法给您单独添加此功能，还请您理解 
 
 ________________________________ 
 发件人: yinking1203 <notifications@github.com&gt; 
 发送时间: Thursday, October 31, 2019 5:41:31 PM 
 收件人: kongzue/DialogV3 <DialogV3@noreply.github.com&gt; 
 抄送: Kongzue <myzcxhh@live.cn&gt;; Comment <comment@noreply.github.com&gt; 
 主题: Re: [kongzue/DialogV3] 希望在3.15版本中 增加 dialog 占屏幕比例 API入口 尤其是自定义dialog布局 (#76) 
 
 &amp;nbsp;麻烦您了 &amp;nbsp; 嗯 &amp;nbsp;setAlign 这个我知道 &amp;nbsp;只是 写死高度 或者 依靠 margin &amp;nbsp;来控制高度 &amp;nbsp;会不会不太友好 适配的话 估计也会有问题 
 &amp;nbsp; 
 
 
 ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------ 
 发件人:&amp;nbsp;"notifications"<notifications@github.com&amp;gt;; 
 发送时间:&amp;nbsp;2019年10月31日(星期四) 下午5:32 
 收件人:&amp;nbsp;"kongzue/DialogV3"<DialogV3@noreply.github.com&amp;gt;; 
 抄送:&amp;nbsp;"尹江峰"<526241452@qq.com&amp;gt;;"Author"<author@noreply.github.com&amp;gt;; 
 主题:&amp;nbsp;Re: [kongzue/DialogV3] 希望在3.15版本中 增加 dialog 占屏幕比例 API入口 尤其是自定义dialog布局 (#76) 
 
 
 
 
 CustomDialog可以设置从屏幕底端显示： 
 CustomDialog.setAlign(CustomDialog.ALIGN.BOTTOM) //从屏幕底端出现 
 然后您可以只做一个一半屏幕高度的布局即可 
 
 ― 
 You are receiving this because you authored the thread. 
 Reply to this email directly, view it on GitHub, or unsubscribe. 
 
 ―
