### ISSUE TITLE
How can I get back the animation before using the .dismiss() method in the FullScreenDialog?

### ISSUE THREAD

**Issue by taksumaki** [kongzue/DialogV3#99]
I am noticing that the effect of the method .dismiss() is now like a fading, I really loved the other effect, that the effect was the same as the input but inverted, and was hidden in a very elegant way. I am using the Beta version **3.1.6.1**.  

Also the FullScreenDialog does not reach the notification bar so that it is considered full, I am testing on a Redmi Note 6.

**Comment by kongzue** [comment]
I'm sorry that there are no settings currently used to change the animation effect of the dialog box, but you can use this setting to change it:
```
DialogSettings.systemDialogStyle = R.style.customDialogStyle;
```
then create a custom style file customDialogStyle
```
<style name="customDialogStyle" parent="BaseDialog">
        <item name="android:windowAnimationStyle">@style/dialogAnim</item>
</style>

<style name="dialogAnim">
    <item name="android:windowEnterAnimation">@anim/bottom_menu_enter</item>
    <item name="android:windowExitAnimation">@anim/bottom_menu_exit</item>
</style>
```
FullScreenDialog does not reach the notification bar because features  LAYOUT_IN_DISPLAY_CUTOUT_MODE_SHORT_EDGES are not supported in earlier versions of the system,I will try to fix this problem.

**Comment by taksumaki** [comment]
Thanks.
